export const SEND_MESSAGE_REQUEST = '@@chat/SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = '@@chat/SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAILURE = '@@chat/SEND_MESSAGE_FAILURE'

export const GET_MESSAGE_REQUEST = '@@chat/GET_MESSAGE_REQUEST'
export const GET_MESSAGE_SUCCESS = '@@chat/GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAILURE = '@@chat/GET_MESSAGE_FAILURE'